### ISSUE TITLE
Problem walidacji pola

### ISSUE THREAD

**Issue by rozwand** [mateusz-stelmasiak/Prestashop-Module-ParagonCzyFaktura#1]
Nie ma walidacji pola NIP.
Drugi błąd to że po wpisaniu i zapisaniu faktury nip/nazwa firmy nie można zmienić już tych danych.

**Comment by mateusz-stelmasiak** [comment]
Hej, dzięki za feedback. 
W najnowszym release'ie [(tutaj)](https://github.com/mateusz-stelmasiak/Prestashop-Module-ParagonCzyFaktura/releases/tag/v1.2.0) powinno być naprawione wszystko o czym wspominałaś/eś.

**Comment by rozwand** [comment]
Ale jak robisz nową wersję wypadało by dać chociaż
` $this->version = '1.0.1'; na  $this->version = '1.0.2'; `
to samo w 
`<version><![CDATA[1.0.1]]></version> na <version><![CDATA[1.0.2]]></version>`

I takie śmieci też powinieneś oczyścić w module.

`a:1:{i:0;C:46:"Symfony\Component\Config\Resource\FileResource":72:{s:64:"/home/alhambra/ftp/alhambrasklep/themes/classic/config/theme.yml";}}`


Wydaje mi się że to zapytanie paragin/faktura powinno być w momencie gdy ktoś jest w ADRESY i tam dać mu możliwość wyboru paragon lub faktura i na podstawie wybranej opcji pokazywały by mu się wszystkie inputy.
Coś tak jak jest na [botland](https://botland.com.pl/)


Jeśli wybrał by paragon nie było by pola firma i nip, a gdy wybrał by fakturę było by pokazane pole firma i nip. Można nawet ukryć te pola za pomocą css
